import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { set, useForm } from "react-hook-form";
import useSWR from "swr";
import Head from 'next/head'
import Image from 'next/image'
import mainIllustration from '../public/assets/images/main-illustration.svg'
import bookRoomIllustration from '../public/assets/images/book-room-illustration.svg'
import jalaSeater from '../public/assets/images/jala-seater.svg'
import moment from "moment/moment";
import Script from 'next/script';
import CreateReservationModal from "../components/modals/CreateReservationModal";
import LeaveModal from "../components/modals/LeaveModal";
import SeatMap from "../components/SeatMap";
import axios from "axios";
import MyReservedDetailModal from "../components/modals/MyReservedDetailModal";

export default function Home() {
  const [selectedSeat, setSelectedSeat] = useState("");
  const [generateTicket, setGenerateTicket] = useState(selectedSeat + moment().format("ADDMMYYh"));
  const [loading, setLoading] = useState(true);
  const [data, setData] = useState();
  const [rowA, setRowA] = useState({});
  const [rowB, setRowB] = useState({});
  const [rowC, setRowC] = useState({});
  const [rowD, setRowD] = useState({});
  const [bookModel, setBookModel] = useState({});
  const [reservationShow, setReservationShow] = useState({});
  
  const checkingReservation = () => {
    if (localStorage.getItem('seatReservation') && localStorage.getItem('seatReservation') === {}){
      return false;
    } else {
      return true;
    }
  }
  // console.log('checkingReservation',checkingReservation())
  const fetcher = async (url) => await axios.get(url, {
    headers: {
      Authorization: `Bearer ${process.env.AIRTABLE_API_KEY}`,
      Accept: "application/json",
      "Content-Type": "application/json",
    },
  }).then(res => {
    setData(res.data); 
    setRowA(res.data.records.filter((i)=>(i.fields.row_name == "A")))
    setRowB(res.data.records.filter((i)=>(i.fields.row_name == "B")))
    setRowC(res.data.records.filter((i)=>(i.fields.row_name == "C")))
    setRowD(res.data.records.filter((i)=>(i.fields.row_name == "D")))
  }).catch(error=>console.error(error)).finally(()=>{setLoading(false)})

  const {seatData,error} = useSWR(`https://api.airtable.com/v0/${process.env.AIRTABLE_BASE}/chair?sort%5B0%5D%5Bfield%5D=id&sort%5B0%5D%5Bdirection%5D=desc`, (url) =>fetcher(url));

  if (error) {
    return (
      <div className="position-relative">
        <div className="mt-5 position-absolute top-50 start-50 translate-middle">
          <b className="alert alert-danger" role="alert">😒 We'll be back</b>
        </div>
      </div>
    )
  }
  if(loading == true){
    return (
      <div className="h-100">
        <div className="d-flex justify-content-center h-100" style={{minHeight:"100vh"}}>
          <div className="spinner-border text-primary" role="status" style={{alignSelf:"center",width:"3rem",height:"3rem"}}>
            <span className="visually-hidden">Loading...</span>
          </div>
        </div>
      </div>
    );
  } else {
    return (
      <div style={{maxWidth:"100vw"}}>
        <Head>
          <title>JALA Seater</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/icon.png" />
        </Head>
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous" />
  
        <main>
          <header>
            <nav className="navbar bg-primary fixed-top">
              <div className="container">
                <div className="d-flex justify-content-between w-100">
                  <div className="">
                    <a className="navbar-brand text-white" href="#">
                      <Image
                        src={jalaSeater}
                        className="logo"
                        alt="mainIllustration"
                        height={48}
                      />
                    </a>
                  </div>
                  <div className="align-self-center">
                    <button className="btn btn-danger" type="submit" data-bs-toggle="modal" data-bs-target="#leaveModal">Tinggalkan Kursi</button>
                  </div>
                </div>
              </div>
            </nav>
          </header>
          <div className='container mt-5 pt-5 pt-md-5'>
            <div className="row">
              <div className="col-sm-12 col-md-6 mt-3">
                <h5>Halo, Warga Jala👋</h5>
                <div className="card">
                  <div className="card-body">
                    <div className="row">
                      <div className="col-auto">
                        <Image
                          src={mainIllustration}
                          alt="mainIllustration"
                          height={144}
                        />
                      </div>
                      <div className="col d-flex flex-column h-100 justify-content-start">
                        <h2 className='text-primary'>{moment().format("h:mm A")}</h2>
                        <span>{moment().format("ddd, DD MMM YYYY")}</span>
                        <p>🏢 Sahid J-Walk (Yogyakarta)</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-sm-12 col-md-6 mt-3">
                <h5>Upcoming Feature</h5>
                <div className="card">
                  <div className="card-body">
                    <div className="row">
                      <div className="col-auto">
                        <Image
                          src={bookRoomIllustration}
                          alt="bookRoomIllustration"
                          height={144}
                        />
                      </div>
                      <div className="col d-flex flex-column h-100 justify-content-start">
                        <h2 className='text-primary'>Booking Ruangan!</h2>
                        <p>Kini kamu bisa booking ruangan dengan mudah loooh..</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <SeatMap
            rowA={rowA}
            rowB={rowB}
            rowC={rowC}
            rowD={rowD}
            seat={val => setSelectedSeat(val)}
            reservationShow={val => setReservationShow(val)}
          />
          {checkingReservation() == true ? (
            <CreateReservationModal
              seats={data}
              seatNumber={selectedSeat}
              generateTicket={generateTicket}
              reservationShow={val => setReservationShow(val)}
            />
          ) : (
            <MyReservedDetailModal/>
          )}
          <LeaveModal/>
          <nav className="navbar bg-primary fixed-bottom">
            <div className="d-flex justify-content-center w-100">
              <b className="text-white">😆Ini Tembok Depan Guys..</b>
            </div>
          </nav>
        </main>
      </div>
    )
  }
}
