import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { useForm } from "react-hook-form";
import useSWR from "swr";
import axios from "axios";
import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import mainIllustration from '../public/assets/images/main-illustration.svg'
import bookRoomIllustration from '../public/assets/images/book-room-illustration.svg'
import chairOutline from '../public/assets/images/chair-outline.svg'
import chairBlue from '../public/assets/images/chair-blue.svg'
import chairGreen from '../public/assets/images/chair-green.svg'
import jalaSeater from '../public/assets/images/jala-seater.svg'
import moment from "moment/moment";
import Script from 'next/script'

const fetcher = async (
  input = RequestInfo,
  init = RequestInit,
) => {
  const res = await fetch(input, init);
  return res.json();
};
// const fetcher = (...args) => fetch(...args).then((res) => res.json());

export default function Home() {
  const { register, handleSubmit, formState: { errors } } = useForm();
  const [loading, setLoading] = useState(true);
  const [selectedSeat, setSelectedSeat] = useState("");
  const [rowA, setRowA] = useState({});
  const [rowB, setRowB] = useState({});
  const [rowC, setRowC] = useState({});
  const [rowD, setRowD] = useState({});

  useEffect(() => {
    // setRowA(fetchSeats.data.records.filter((i)=>(i.row_name == "A")))
    // setRowB(fetchSeats.data.records.filter((i)=>(i.row_name == "B")))
    // setRowC(fetchSeats.data.records.filter((i)=>(i.row_name == "C")))
    // setRowD(fetchSeats.data.records.filter((i)=>(i.row_name == "D")))
    return () => {
        // alert('mounted')
    }
  })

  const onSubmit = data => {
    console.log('onSubmit', data);
    bookingSeat(data);
  }
  
  const router = useRouter();

  const fetchSeats = useSWR(
    `https://api.airtable.com/v0/${process.env.AIRTABLE_BASE}/chair`,
    (url) =>
      fetcher(url, {
        headers: {
          Authorization: `Bearer ${process.env.AIRTABLE_API_KEY}`,
          Accept: "application/json",
        },
      }).finally((response)=>{
        console.log(response)
        setLoading(false)
      })
  );
  
  const bookingSeat = async (data) => {
    const value = 
      [
        {
          "fields":{
            "name": data.name,
            "email": data.email,
            "reservation_date": moment().format("MM/DD/YYYY"),
            "reservation_code": selectedSeat + moment().format("ADDMMYYh"),
            "chair_number": selectedSeat
          }
        }
      ]
    ;
    await fetcher(`https://api.airtable.com/v0/${process.env.AIRTABLE_BASE}/reservation`, {
      method: "PATCH",
      body: JSON.stringify(value),
      headers: {
        Authorization: `Bearer ${process.env.AIRTABLE_API_KEY}`,
        Accept: "application/json",
      },
    })
    // .then((response) => response.text())
    .then(result => console.log(result))
    .catch((error) => console.log("error", error));;
  };
  // console.log("CreateData",CreateData)
  console.log('AIRTABLE_BASE:',process.env.AIRTABLE_BASE)
  console.log('AIRTABLE_API_KEY:',process.env.AIRTABLE_API_KEY)
  // console.log('fetchSeats:',fetchSeats)
  // console.log('modelData',modelData)
  // console.log("bookingSeat",bookingSeat)
  if(loading == true){
    return (
      <div className="h-100">
        <div className="d-flex justify-content-center h-100" style={{minHeight:"100vh"}}>
          <div className="spinner-border text-primary" role="status" style={{alignSelf:"center",width:"3rem",height:"3rem"}}>
            <span className="visually-hidden">Loading...</span>
          </div>
        </div>
      </div>
    );
  } else {
    return (
      <div style={{maxWidth:"100vw"}}>
        <Head>
          <title>JALA Seater</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/icon.png" />
        </Head>
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous" />
  
        <main>
          <header>
            <nav className="navbar bg-primary fixed-top">
              <div className="container">
                <div className="d-flex justify-content-between w-100">
                  <div className="">
                    <a className="navbar-brand text-white" href="#">
                      <Image
                        src={jalaSeater}
                        className="logo"
                        alt="mainIllustration"
                        height={48}
                      />
                    </a>
                  </div>
                  <div className="align-self-center">
                    <button className="btn btn-danger" type="submit" data-bs-toggle="modal" data-bs-target="#leaveModal">Tinggalkan Kursi</button>
                  </div>
                </div>
              </div>
            </nav>
          </header>
          <div className='container mt-5 pt-5 pt-md-5'>
            <div className="row">
              <div className="col-sm-12 col-md-6 mt-3">
                <h5>Halo, Warga Jala👋</h5>
                <div className="card">
                  <div className="card-body">
                    <div className="row">
                      <div className="col-auto">
                        <Image
                          src={mainIllustration}
                          alt="mainIllustration"
                          height={144}
                        />
                      </div>
                      <div className="col d-flex flex-column h-100 justify-content-start">
                        <h2 className='text-primary'>{moment().format("h:mm A")}</h2>
                        <span>{moment().format("ddd, DD MMM YYYY")}</span>
                        <p>🏢 Sahid J-Walk (Yogyakarta)</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-sm-12 col-md-6 mt-3">
                <h5>Upcoming Feature</h5>
                <div className="card">
                  <div className="card-body">
                    <div className="row">
                      <div className="col-auto">
                        <Image
                          src={bookRoomIllustration}
                          alt="bookRoomIllustration"
                          height={144}
                        />
                      </div>
                      <div className="col d-flex flex-column h-100 justify-content-start">
                        <h2 className='text-primary'>Booking Ruangan!</h2>
                        <p>Kini kamu bisa booking ruangan dengan mudah loooh..</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {/* kursi */}
          <div className="container">
            {/* Baris D */}
            <div className="row mt-3 mx-md-5">
              <div className="col-12">
                <div className='d-flex justify-content-between gap-3 w-100'>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('D10')}} data-bs-toggle="modal" data-bs-target="#exampleModal">
                      <Image
                        src={chairGreen}
                        alt="tersedia"
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('D9')}} data-bs-toggle="modal" data-bs-target="#exampleModal">
                      <Image
                        src={chairGreen}
                        alt="tersedia"
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('D8')}} data-bs-toggle="modal" data-bs-target="#exampleModal">
                      <Image
                        src={chairGreen}
                        alt="tersedia"
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('D7')}} data-bs-toggle="modal" data-bs-target="#exampleModal">
                      <Image
                        src={chairGreen}
                        alt="tersedia"
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('D6')}} data-bs-toggle="modal" data-bs-target="#exampleModal">
                      <Image
                        src={chairGreen}
                        alt="tersedia"
                      />
                    </a>
                  </div>
                </div>
              </div>
              <div className="col-12">
                <div className="d-flex w-100 justify-content-center" style={{height:"35px",backgroundColor:"#E9D6C1"}}>
                  <b className="text-center w-100">Baris D</b>
                </div>
              </div>
              <div className="col-12">
                <div className='d-flex justify-content-between gap-3 w-100'>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('D5')}} data-bs-toggle="modal" data-bs-target="#exampleModal">
                      <Image
                        src={chairGreen}
                        alt="tersedia"
                        className='rotate-180'
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('D4')}} data-bs-toggle="modal" data-bs-target="#exampleModal">
                      <Image
                        src={chairGreen}
                        alt="tersedia"
                        className='rotate-180'
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('D3')}} data-bs-toggle="modal" data-bs-target="#exampleModal">
                      <Image
                        src={chairGreen}
                        alt="tersedia"
                        className='rotate-180'
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('D2')}} data-bs-toggle="modal" data-bs-target="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                        className='rotate-180'
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('D1')}} data-bs-toggle="modal" databstarget="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                        className='rotate-180'
                      />
                    </a>
                  </div>
                </div>
              </div>
            </div>
            {/* Baris C */}
            <div className="row mt-3 mx-md-5">
              <div className="col-12">
                <div className='d-flex justify-content-between gap-3 w-100'>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('C10')}} data-bs-toggle="modal" data-bs-target="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('C9')}} data-bs-toggle="modal" data-bs-target="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#"  onClick={()=>{setSelectedSeat('C8')}} data-bs-toggle="modal" data-bs-target="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('C7')}} data-bs-toggle="modal" data-bs-target="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('C6')}} data-bs-toggle="modal" data-bs-target="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                      />
                    </a>
                  </div>
                </div>
              </div>
              <div className="col-12">
                <div className="d-flex w-100 justify-content-center" style={{height:"35px",backgroundColor:"#E9D6C1"}}>
                  <b className="text-center w-100">Baris C</b>
                </div>
              </div>
              <div className="col-12">
                <div className='d-flex justify-content-between gap-3 w-100'>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('C5')}} data-bs-toggle="modal" databstarget="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                        className='rotate-180'
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('C4')}} data-bs-toggle="modal" databstarget="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                        className='rotate-180'
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('C3')}} data-bs-toggle="modal" databstarget="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                        className='rotate-180'
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('C2')}} data-bs-toggle="modal" databstarget="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                        className='rotate-180'
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('C1')}} data-bs-toggle="modal" databstarget="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                        className='rotate-180'
                      />
                    </a>
                  </div>
                </div>
              </div>
            </div>
            {/* Baris B */}
            <div className="row mt-3 mx-md-5">
              <div className="col-12">
                <div className='d-flex justify-content-between gap-3 w-100'>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('B10')}} data-bs-toggle="modal" data-bs-target="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('B9')}} data-bs-toggle="modal" data-bs-target="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('B8')}} data-bs-toggle="modal" data-bs-target="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('B7')}} data-bs-toggle="modal" data-bs-target="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('B6')}} data-bs-toggle="modal" data-bs-target="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                      />
                    </a>
                  </div>
                </div>
              </div>
              <div className="col-12">
                <div className="d-flex w-100 justify-content-center" style={{height:"35px",backgroundColor:"#E9D6C1"}}>
                  <b className="text-center w-100">Baris B</b>
                </div>
              </div>
              <div className="col-12">
                <div className='d-flex justify-content-between gap-3 w-100'>
                  <div>
                  <a href="#" onClick={()=>{setSelectedSeat('B5')}} data-bs-toggle="modal" databstarget="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                        className='rotate-180'
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('B4')}} data-bs-toggle="modal" databstarget="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                        className='rotate-180'
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('B3')}} data-bs-toggle="modal" databstarget="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                        className='rotate-180'
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('B2')}} data-bs-toggle="modal" databstarget="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                        className='rotate-180'
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('B1')}} data-bs-toggle="modal" databstarget="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                        className='rotate-180'
                      />
                    </a>
                  </div>
                </div>
              </div>
            </div>
            {/* Baris A */}
            <div className="row mt-3 mx-md-5">
              <div className="col-12">
                <div className='d-flex justify-content-between gap-3 w-100'>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('A10')}} data-bs-toggle="modal" data-bs-target="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('A9')}} data-bs-toggle="modal" data-bs-target="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('A8')}} data-bs-toggle="modal" data-bs-target="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('A7')}} data-bs-toggle="modal" data-bs-target="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('A6')}} data-bs-toggle="modal" data-bs-target="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                      />
                    </a>
                  </div>
                </div>
              </div>
              <div className="col-12">
                <div className="d-flex w-100 justify-content-center" style={{height:"35px",backgroundColor:"#E9D6C1"}}>
                  <b className="text-center w-100">Baris A</b>
                </div>
              </div>
              <div className="col-12">
                <div className='d-flex justify-content-between gap-3 w-100'>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('A5')}} data-bs-toggle="modal" databstarget="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                        className='rotate-180'
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('A4')}} data-bs-toggle="modal" databstarget="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                        className='rotate-180'
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('A3')}} data-bs-toggle="modal" databstarget="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                        className='rotate-180'
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('A2')}} data-bs-toggle="modal" databstarget="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                        className='rotate-180'
                      />
                    </a>
                  </div>
                  <div>
                    <a href="#" onClick={()=>{setSelectedSeat('A1')}} data-bs-toggle="modal" databstarget="#exampleModal">
                      <Image
                        src={chairOutline}
                        alt="tersedia"
                        className='rotate-180'
                      />
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
            
          {/* note */}
          <div className="row mt-4 mb-5">
            <div className="col-12" style={{marginBottom:"72px"}}>
              <div className='d-flex justify-content-center gap-4'>
                <div>
                  <Image
                    src={chairOutline}
                    alt="tersedia"
                  />
                  <span>Tersedia</span>
                </div>
                {/* <div>
                  <Image
                    src={chairBlue}
                    alt="dipilih"
                  />
                  <span>Dipilih</span>
                </div> */}
                <div>
                  <Image
                    src={chairGreen}
                    alt="terbooking"
                  />
                  <span>Terbooking</span>
                </div>
              </div>
            </div>
          </div>
          {/* modal */}
          <div className="modal fade" id="exampleModal" tabIndex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div className="modal-dialog modal-dialog-centered">
              <div className="modal-content">
                <div className="modal-header">
                  <h5 className="modal-title" id="exampleModalLabel">Pilih Kursi</h5>
                  <button type="button" className="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form onSubmit={handleSubmit(onSubmit)}>
                  <div className="modal-body">
                    <div>
                      <div className="mb-3">
                        <label htmlFor="exampleInputName1" className="form-label">Nama</label>
                        <input {...register("name",{ required: true })} aria-invalid={errors.name ? "true" : "false"} type="text" className="form-control" id="exampleInputName1"/>
                        {errors.name && <div className="invalid-feedback" role="alert">{errors.name?.message}</div>}
                      </div>
                      <div className="mb-3">
                        <label htmlFor="exampleInputName1" className="form-label">Email</label>
                        <input {...register("email",{ required: true })} aria-invalid={errors.email ? "true" : "false"} type="text" className="form-control" id="exampleInputName1"/>
                        {errors.email && <div className="invalid-feedback" role="alert">{errors.email?.message}</div>}
                      </div>
                      <div className="mb-3">
                        <label htmlFor="exampleInputName1" className="form-label">No. Kursi</label>
                        <input disabled type="text" value={selectedSeat} className="form-control" id="exampleInputName1"/>
                      </div>
                      <div className="mb-3">
                        <label htmlFor="exampleInputName1" className="form-label">Tanggal booking</label>
                        <input disabled type="text" value={moment().format("MM/DD/YYYY")} className="form-control" id="exampleInputName1"/>
                      </div>
                    </div>
                  </div>
                  <div className="modal-footer">
                    <button type="button" className="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" className="btn btn-primary">Booking</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
          {/* modal leave */}
          <div className="modal fade" id="leaveModal" tabIndex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div className="modal-dialog modal-dialog-centered">
              <div className="modal-content">
                <div className="modal-header">
                  <h5 className="modal-title" id="exampleModalLabel">Tinggalkan kursi</h5>
                  <button type="button" className="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                  <div className="modal-body">
                    <div>
                      <div className="mb-3">
                        <label htmlFor="exampleInputName1" className="form-label">No.Tiket</label>
                        <input value={selectedSeat + moment().format("ADDMMYYh")} type="text" className="form-control" id="exampleInputName1"/>
                      </div>
                      <div className="mb-3">
                        <label htmlFor="exampleInputName1" className="form-label">Nama</label>
                        <input disabled value="Muhammad Amien" type="text" className="form-control" id="exampleInputName1"/>
                      </div>
                      <div className="mb-3">
                        <label htmlFor="exampleInputName1" className="form-label">Email</label>
                        <input disabled value="muhammadamien23@gmail.com" aria-invalid={errors.email ? "true" : "false"} type="text" className="form-control" id="exampleInputName1"/>
                      </div>
                      <div className="mb-3">
                        <label htmlFor="exampleInputName1" className="form-label">No. Kursi</label>
                        <input disabled type="text" value={selectedSeat} className="form-control" id="exampleInputName1"/>
                      </div>
                      <div className="mb-3">
                        <label htmlFor="exampleInputName1" className="form-label">Tanggal booking</label>
                        <input disabled type="text" value={moment().format("MM/DD/YYYY")} className="form-control" id="exampleInputName1"/>
                      </div>
                    </div>
                  </div>
                  <div className="modal-footer">
                    <button type="button" className="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" className="btn btn-danger">Leave</button>
                  </div>
              </div>
            </div>
          </div>
          <nav className="navbar bg-primary fixed-bottom">
            <div className="d-flex justify-content-center w-100">
              <b className="text-white">😆Ini Tembok Depan Guys..</b>
            </div>
          </nav>
        </main>
      </div>
    )
  }
}
